#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
# SSL key logging
export SSLKEYLOGFILE=~/.sslkeylog
export SSH_ASKPASS=ssh-askpass
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd_hrgb'
export TERM=screen-256color
export EDITOR="emacs"
